//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "txs")]
pub struct Model {
    pub hash: Option<String>,
    pub vins: Option<String>,
    pub vinaddrs: Option<Json>,
    pub vinamts: Option<Json>,
    pub voutaddrs: Option<Json>,
    pub voutamts: Option<Json>,
    pub blocknum: Option<i64>,
    pub confirmations: Option<i64>,
    pub fee: Option<Decimal>,
    pub size: Option<i64>,
    pub extra: Option<String>,
    pub outputindices: Option<Json>,
    pub ringsize: Option<i64>,
    pub timestamp: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
