[package]
name = "_External_crates_rayon_serde_157"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elapsed = "0.1.2"
rayon = "1.7.0"
serde = "1.0.180"
